DROP TABLE IF EXISTS STUDENTS; 


CREATE TABLE EMPLOYEE (

Emp_name TEXT NOT NULL , 
Emp_number INTEGER NOT NULL, 
Emp_addr TEXT NOT NULL
);

INSERT INTO EMPLOYEE VALUES 
('Dr.TANJUMUL' , '01712987393', 'GAIBANDHA'), 
('Brother Tanvir' , '0333223239', 'RANGPUR'), 
('Someone is so special and important in my life ma', '0183242448' , 'GAIBANDHA');


SELECT * FROM EMPLOYEE;