DROP TABLE IF EXISTS STUDENTS; 


CREATE TABLE EMPLOYEE (

Emp_name TEXT NOT NULL , 
Emp_number INTEGER NOT NULL, 
Emp_addr TEXT NOT NULL
);

INSERT INTO EMPLOYEE VALUES 
('TANJUMUL ALOM SIAM' , '01712987393', 'GAIBANDHA'), 
('TANVIR RAHMAN SOAD' , '0333223239', 'RANGPUR'), 
('TAHMINA BANU', '0183242448' , 'GAIBANDHA');


SELECT * FROM EMPLOYEE;